version: '3.8'

services:
  symfony_app_cook_sphere:
    build:
      context: ./cook_sphere/
      dockerfile: Dockerfile
    container_name: symfony_app_cook_sphere
    ports:
      - "8000:8000"
    volumes:
      - ./cook_sphere:/app:delegated
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:1234@database:5432/app?serverVersion=16&charset=utf8"

  database:
    image: postgres:16
    container_name: cook_sphere-database-1
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-cook_sphere
    ports:
      - 8080:8080
    depends_on:
      - database
  
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-cook_sphere
    ports:
      - "8090:8025"

volumes:
  db_data:
